name: Aproval
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build
              run:  echo "Build is ready!"
    manual_approval:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Waiting for approval
              run: |
                echo "Waiting for manual approval..."
                sleep 600 # Replace with an approval mechanism if needed
    deploy:
        runs-on: ubuntu-latest
        needs: manual_approval
        steps:
            - name: Deploy
              run: echo "Deploying..."