name: Aproval
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build
              run:  echo "Build is ready!"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: development
        steps:
            - name: Deploy
              run: echo "Deploying..."