name: Hello Schedule

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  hello_scheduled_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
